<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20447" started-at="2020-03-18T16:48:49 IST" finished-at="2020-03-18T16:49:09 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20447" started-at="2020-03-18T16:48:49 IST" finished-at="2020-03-18T16:49:09 IST">
      <class name="AllureReports.Tests">
        <test-method status="PASS" signature="setupextent()[pri:0, instance:AllureReports.Tests@63a5e46c]" name="setupextent" is-config="true" duration-ms="263" started-at="2020-03-18T16:48:48 IST" finished-at="2020-03-18T16:48:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupextent -->
        <test-method status="PASS" signature="setup()[pri:0, instance:AllureReports.Tests@63a5e46c]" name="setup" is-config="true" duration-ms="16442" started-at="2020-03-18T16:48:49 IST" finished-at="2020-03-18T16:49:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="LogoPresence()[pri:1, instance:AllureReports.Tests@63a5e46c]" name="LogoPresence" duration-ms="169" started-at="2020-03-18T16:49:05 IST" description="verify logo presence on home page" finished-at="2020-03-18T16:49:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoPresence -->
        <test-method status="PASS" signature="results(org.testng.ITestResult)[pri:0, instance:AllureReports.Tests@63a5e46c]" name="results" is-config="true" duration-ms="15" started-at="2020-03-18T16:49:05 IST" finished-at="2020-03-18T16:49:05 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LogoPresence status=SUCCESS method=Tests.LogoPresence()[pri:1, instance:AllureReports.Tests@63a5e46c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- results -->
        <test-method status="FAIL" signature="logintest()[pri:2, instance:AllureReports.Tests@63a5e46c]" name="logintest" duration-ms="2410" started-at="2020-03-18T16:49:06 IST" finished-at="2020-03-18T16:49:08 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [nopCommerce demo store.j Login] but found [nopCommerce demo store. Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store.j Login] but found [nopCommerce demo store. Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at AllureReports.Tests.logintest(Tests.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method status="PASS" signature="results(org.testng.ITestResult)[pri:0, instance:AllureReports.Tests@63a5e46c]" name="results" is-config="true" duration-ms="355" started-at="2020-03-18T16:49:08 IST" finished-at="2020-03-18T16:49:08 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logintest status=FAILURE method=Tests.logintest()[pri:2, instance:AllureReports.Tests@63a5e46c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- results -->
        <test-method status="SKIP" signature="Resgistration()[pri:3, instance:AllureReports.Tests@63a5e46c]" name="Resgistration" duration-ms="3" started-at="2020-03-18T16:49:08 IST" finished-at="2020-03-18T16:49:08 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skipping this test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skipping this test
at AllureReports.Tests.Resgistration(Tests.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Resgistration -->
        <test-method status="PASS" signature="results(org.testng.ITestResult)[pri:0, instance:AllureReports.Tests@63a5e46c]" name="results" is-config="true" duration-ms="1" started-at="2020-03-18T16:49:08 IST" finished-at="2020-03-18T16:49:08 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Resgistration status=SKIP method=Tests.Resgistration()[pri:3, instance:AllureReports.Tests@63a5e46c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- results -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:AllureReports.Tests@63a5e46c]" name="teardown" is-config="true" duration-ms="758" started-at="2020-03-18T16:49:08 IST" finished-at="2020-03-18T16:49:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="endreport()[pri:0, instance:AllureReports.Tests@63a5e46c]" name="endreport" is-config="true" duration-ms="690" started-at="2020-03-18T16:49:09 IST" finished-at="2020-03-18T16:49:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endreport -->
      </class> <!-- AllureReports.Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
